### ISSUE TITLE
Enhancing Logging

### ISSUE THREAD

**Issue by tfechner** [ubergesundheit/dialogmap#7]
We're currently not logging if the page is visible or hidden and the user is browsing on some other website / tab and we don't know when the page / browser is closed. For the former the page visibility API seems to be a good candidate. Page closing events need some thought.

**Comment by ubergesundheit** [comment]
resolved in https://github.com/sitcomlab/dialogmap-sustainabilitymap/commit/a4f8e24177461bccf7709075515bfba2faf6073c
